apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "busybox.fullname" . }}
  labels:
    app: {{ include "busybox.name" . }}
    chart: {{ include "busybox.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "busybox.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "busybox.name" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/version:  "{{ .Chart.AppVersion }}"
        app.kubernetes.io/part-of : {{ include "busybox.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DT_TAGS
              value: release={{ .Release.Name }} app={{ include "busybox.name" . }}
            - name: DT_RELEASE_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: DT_RELEASE_STAGE
              value: {{ .Values.stage }}
            - name: DT_RELEASE_PRODUCT
              value: {{ include "busybox.fullname" . }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
