apiVersion: v1
kind: Service
metadata:
  name: {{ include "busybox.fullname" . }}
  labels:
    app: {{ include "busybox.name" . }}
    chart: {{ include "busybox.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/part-of: { { include "busybox.fullname" . } }
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "busybox.name" . }}
    release: {{ .Release.Name }}
