resources:
  - name: helmGitHub
    type: GitRepo
    configuration:
      gitProvider: DT_PIPELINE
      # replace with your pipelines repository
      path: JFrogDynatrace/pipelines-demo # if path is modified, change the name as well, per Pipelines doc
      branches:
        include: main
      buildOn:
        commit: true

  - name: simpleDockerImage # change
    type: Image
    configuration:
      registry: simplehelmDockerIntegration
      sourceRepository: art-docker-dynatrace
      imageName: dynatracejtpp.jfrog.io/art-docker-dynatrace/busybox
      imageTag: '${run_number}'

  - name: simpleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: SampleApp
      buildNumber: 1

  - name: simpleHelmChartBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: SampleApp
      buildNumber: '0.1.${run_number}'

  - name: simplehelmRepoChart
    type: GitRepo
    configuration:
      gitProvider: DT_PIPELINE
      path: JFrogDynatrace/pipelines-demo # replace with your repo
      branches:
        include: main
      buildOn:
        commit: true

  - name: simplehelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: artifactoryIntegration
      repository: simplecharts
      chart: busybox
      version: 0.0.0

pipelines:
  - name: dynatrace_demo_helm
    configuration:
      environmentVariables:
        readOnly:
          my_releaseName: "busyboxpipeline${run_number}"
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: buildAndPush
          integrations:
            - name: artifactoryIntegration
          inputResources:
            - name: helmGitHub
          dockerFileLocation: pipeline/dynatrace/
          dockerFileName: Dockerfile
          dockerImageName: dynatracejtpp.jfrog.io/art-docker-dynatrace/busyboxpipeline
          dockerImageTag: $run_number

      - name: push_image
        type: DockerPush
        configuration:
          affinityGroup: buildAndPush
          autoPublishBuildInfo: true
          integrations:
            - name: artifactoryIntegration
          targetRepository: art-docker-dynatrace
          inputSteps:
            - name: build_image
          outputResources:
            - name: simpleBuildInfo
            - name: simpleDockerImage

      - name: helm_build
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: pipeline/dynatrace/busybox/
          affinityGroup: helm_install
          inputSteps:
            - name: push_image
          inputResources:
            - name: simplehelmRepoChart
              trigger: false
          outputResources:
            - name: simplehelmChart
            - name: simpleHelmChartBuildInfo
        execution:
          onStart:
            - echo "Start"
            - printenv

      # Install Dynatrace agent on the cluster. Use the separate namespace
      - name: install_oneAgent_operator
        type: Bash
        configuration:
          affinityGroup: helm_install
          integrations:
            - name: k8sIntegration
            - name: dynatraceIntegration
          inputSteps:
            - name: helm_build
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "Installing and configuring OneAgent"
            - kubectl config current-context
            - kubectl get namespace
            - kubectl get pods
            - ACTIVE=$(kubectl get ns dynatrace -o json --ignore-not-found | jq .status.phase -r)
            - >-
              if [[ -z "$ACTIVE" ]]; then
                kubectl create namespace dynatrace;
              fi
            - kubectl apply -f https://github.com/Dynatrace/dynatrace-oneagent-operator/releases/latest/download/kubernetes.yaml
            - kubectl -n dynatrace create secret generic oneagent --from-literal="apiToken=${int_dynatraceIntegration_API_TOKEN}" --from-literal="paasToken=${int_DTEnvInfo_PAAS_TOKEN}"
            - curl -o cr.yaml https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/master/deploy/cr.yaml
            - sed -i "s/ENVIRONMENTID/${int_dynatraceIntegration_API_TOKEN}}/" cr.yaml
            - echo ${int_dynatraceIntegration_DT_URL}
            - cat cr.yaml
            #- sed -i 's/apiUrl:.*/apiUrl:a/b.*'
            ## configure cr.yaml file when we have all the data needed
            - kubectl apply -f cr.yaml
          onSuccess:
            - echo "Dynatrace OneAgent has beed successfully installed"
          onFailure:
            - echo "Failure"

      - name: deploy_helm
        type: HelmDeploy
        configuration:
          helmVersion: 3
          affinityGroup: helm_install
          releaseName: "busyboxpipeline${run_number}"
          integrations:
            - name: k8sIntegration
          inputResources:
            - name: simplehelmChart
            - name: simpleDockerImage
          inputSteps:
            - name: install_oneAgent_operator
          valueFilePaths:
            - values.yaml
        execution:
          onStart:
            - kubectl config current-context
            - add_run_variables CLUSTER="$(kubectl config current-context)"
            - add_run_variables RELEASE_NAME="${my_releaseName}"
            - printenv
          onSuccess:
            - kubectl get pods
          onFailure:
            - echo "Failure"

      - name: modify_properties
        type: Bash
        configuration:
          affinityGroup: helm_install
          integrations:
            - name: artifactoryIntegration
          inputResources:
            - name: simplehelmChart
          inputSteps:
            - name: deploy_helm
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - printenv
            - echo "Modifying helm chart properties"
            - echo "Set current time as a deployment time"
            - TIME=$(date +%s)
            - curl --location --request PUT "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart_version}.tgz?properties=deployedOnCluster=${CLUSTER}%7ChelmInstallationName=${RELEASE_NAME}%7CdeploymentTimestamp=${TIME}" --header "Accept:application/json" --header "X-Jfrog-Art-Api:${int_artifactoryIntegration_apikey}"
          onSuccess:
            - echo ""
          onFailure:
            - echo "Failure"

      - name: Dynatrace_deployment_event
        type: Bash
        configuration:
          affinityGroup: helm_install
          integrations:
            - name: artifactoryIntegration
            - name: dynatraceIntegration
          inputResources:
            - name: simplehelmChart
          inputSteps:
            - name: modify_properties
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - printenv
            - JSONOutput=$(curl --location --request GET "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart_version}.tgz?properties=helmInstallationName,chart.version,deployedOnCluster,vcs.url" --header "Accept:application/json" --header "X-Jfrog-Art-Api:${int_artifactoryIntegration_apikey}" | jq .)
            - echo $JSONOutput
            - ChartVersion=$(echo $JSONOutput | jq '.properties."chart.version"[0]')
            - HelmInstallationName=$(echo $JSONOutput | jq '.properties.helmInstallationName[0]')
            - VCS_URL=$(echo $JSONOutput | jq '.properties."vcs.url"[0]')
            - DeployedOnCluster=$(echo $JSONOutput | jq '.properties.deployedOnCluster[0]')
            - echo $ChartVersion
            - echo $HelmInstallationName
            - echo $run_number
            - echo $build_image_dockerImageName
            - echo $int_artifactoryIntegration_url
            - echo $res_simplehelmChart_version
            - echo curl -H 'Content-Type:application/json' --location --request POST "${int_dynatraceIntegration_DT_URL}/api/v1/events"  -H 'Accept:application/json' -HAuthorization:"Api-Token ${int_dynatraceIntegration_API_TOKEN}" -d "{\"eventType\":\"CUSTOM_DEPLOYMENT\",\"attachRules\":{\"tagRule\":{\"meTypes\":\"SERVICE\",\"tags\":[{\"context\":\"CONTEXTLESS\",\"key\":\"JFrog\",\"value\":\"busybox\"}]}},\"deploymentName\":\"RuntimeDeployment\",\"deploymentVersion\":\"${res_simplehelmChart_version}\",\"deploymentProject\":\"BusyBox-nginx\",\"source\":\"${int_artifactoryIntegration_url}\",\"customProperties\":{\"ChartVersion\":${ChartVersion},\"JFrogArtifactoryUrl\":\"${int_artifactoryIntegration_url}\",\"HelmInstallationName\":${HelmInstallationName},\"RunNumber\":\"${run_number}\",\"DeployedOnCluster\":${DeployedOnCluster},\"VCS_URL\":${VCS_URL},\"DockerImageName\":\"${build_image_dockerImageName}\"}}"
            #- >-
             #curl 
            #- buildNumber="$(${JSONOutput}| jq)"
            #- CLUSTER="$(curl --request GET)"
            - curl -H 'Content-Type:application/json' --location --request POST "${int_dynatraceIntegration_DT_URL}/api/v1/events"  -H 'Accept:application/json' -HAuthorization:"Api-Token ${int_dynatraceIntegration_API_TOKEN}" -d "{\"eventType\":\"CUSTOM_DEPLOYMENT\",\"attachRules\":{\"tagRule\":{\"meTypes\":\"SERVICE\",\"tags\":[{\"context\":\"CONTEXTLESS\",\"key\":\"JFrog\",\"value\":\"busybox\"}]}},\"deploymentName\":\"RuntimeDeployment\",\"deploymentVersion\":\"${res_simplehelmChart_version}\",\"deploymentProject\":\"BusyBox-nginx\",\"source\":\"${int_artifactoryIntegration_url}\",\"customProperties\":{\"ChartVersion\":${ChartVersion},\"JFrogArtifactoryUrl\":\"${int_artifactoryIntegration_url}\",\"HelmInstallationName\":${HelmInstallationName},\"RunNumber\":\"${run_number}\",\"DeployedOnCluster\":${DeployedOnCluster},\"VCS_URL\":${VCS_URL},\"DockerImageName\":\"${build_image_dockerImageName}\"}}"
            #-H "content-type: "
            #- curl -X POST "https\://scu37051.live.dynatrace.com/api/v1/events" --header "accept: application/json"
            #- curl --location --request PUT "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart2_version}.tgz?properties=deployedOnCluster=${CLUSTER}%7ChelmInstallationName=${RELEASE_NAME}%7CdeploymentTimestamp=${TIME}" --header "Accept:application/json" --header "X-Jfrog-Art-Api:${int_artifactoryIntegration_apikey}"
          onSuccess:
            - echo "Event properly sent to ${int_dynatraceIntegration_DT_URL}"
          onFailure:
            - echo "Failure"

      - name: Keptninitproject
        type: Bash
        configuration:
          affinityGroup: launchtest
          integrations:
            - name: KeptnIntegration
          inputSteps:
            - name: Dynatrace_deployment_event
        execution:
          onStart:
            - echo "Initializing the Keptn context ..."
          onExecute:
            - printenv
            - JSONOutput=$(curl --location --request GET "${int_KeptnIntegration_API_URL}/controlPlane/v1/project/${int_KeptnIntegration_PROJECT_NAME}" --header "Accept:application/json" --header "x-token:${int_KeptnIntegration_API_TOKEN}" | jq .)
            - project=$(echo $JSONOutput| jq -r '.projectName')
            - >-
              if [[ ! -z "$project" ]]; then
                 exit 0
              fi
            - sed -i "s/PROJECTTOREPLACE/${int_KeptnIntegration_PROJECT_NAME}/" pipeline/keptn/shipyard.yaml
            - sed -i "s/STAGETOREPLACE/${int_KeptnIntegration_KEPTN_STAGE}/" pipeline/keptn/shipyard.yaml
            - SHIPYARD=$(cat pipeline/keptn/shipyard.yaml | base64)
            - HTTPCODE=$(curl --write-out "%{http_code} --silent --header 'Content-Type:application/json' --location --request POST "${int_KeptnIntegration_API_URL}/controlPlane/v1/project"  -H 'Accept:application/json' --header "x-token:${int_KeptnIntegration_API_TOKEN}" -d "{\"name\":\"${int_KeptnIntegration_PROJECT_NAME}\",\"shipyard\":\"${SHIPYARD}\"}")
            - >-
              if [[ "$HTTPCODE" != "200" ]]; then
                 exit 1
              fi
            - echo "KEPTN project created successfully"
            - HTTPCODE=$(curl --write-out "%{http_code} --silent --header 'Content-Type:application/json' --location --request POST "${int_KeptnIntegration_API_URL}/controlPlane/v1/project/${int_KeptnIntegration_PROJECT_NAME}/service"  -H 'Accept:application/json' --header "x-token:${int_KeptnIntegration_API_TOKEN}" -d "{\"serviceName\":\"${int_KeptnIntegration_SERVICE_NAME}" ")
            - >-
              if [[ "$HTTPCODE" != "200" ]]; then
                exit 1
              fi
            - echo "KEPTN Service created successfully"
            - HTTPCODE=$(curl --write-out "%{http_code}" --silent --header "Content-Type:application/json" --location --request POST "${int_KeptnIntegration_API_URL}/v1/event"  -H 'Accept:application/json' --header "x-token:${int_KeptnIntegration_API_TOKEN}" -d "{\"data\":{ \"project\":\"${int_KeptnIntegration_PROJECT_NAME}\", \"service:\":\"${int_KeptnIntegration_SERVICE_NAME}\", \"type\":\"{int_KeptnIntegration_Monitoring}\"},\"datacontenttype\":\"application/json\",\"source\":\"Jfrog\", \"specversion\" \"1.0\", \"type\":\"sh.keptn.event.monitoring.configure\"}")
            - >-
              if [[ "$HTTPCODE" != "200" ]]; then
                exit 1
              fi
            - echo "KEPTN Monitoring configured"
          onSuccess:
            - echo "Event properly sent to ${int_dynatraceIntegration_DT_URL}"
          onFailure:
            - echo "Failure"

      - name: KeptnMarkEvaluationStartTime
        type: Bash
        configuration:
          affinityGroup: launchtest
          inputSteps:
            - name: Keptninitproject
        execution:
          onStart:
            - echo "Marking test start in Keptn ..."
          onExecute:
            - START_TIME=$(date --utc --iso-8601=seconds)
            - add_run_variables keptnStart="${START_TIME}"                                                                                                                                                                                                                                                                            - SHIPYARD=$(cat pipeline/keptn/shipyard.yaml | base64)
          onSuccess:
            - echo "Event properly sent to ${int_dynatraceIntegration_DT_URL}"
          onFailure:
            - echo "Failure"

      - name: Test
        type: Bash
        configuration:
          affinityGroup: launchtest
          inputSteps:
            - name: KeptnMarkEvaluationStartTime
        execution:
          onStart:
            - echo "Marking test start in Keptn ..."
          onExecute:
            - curl "http://www.dynatrace.com"
            - curl "http://www.dynatrace.com"
            - curl "http://www.dynatrace.com"
          onSuccess:
            - END_TIME=$(date --utc --iso-8601=seconds)
            - add_run_variables keptnEnd="${END_TIME}"
          onFailure:
            - echo "Failure"

      - name: KeptnSendEvaluationEvent
        type: Bash
        configuration:
          affinityGroup: launchtest
          integrations:
            - name: KeptnIntegration
          inputSteps:
            - name: Test
        execution:
          onStart:
            - echo "Sending evaluation event to Keptn for ${int_KeptnIntegration_PROJECT_NAME}.${int_KeptnIntegration_KEPTN_STAGE}.${int_KeptnIntegration_SERVICE_NAME}"
          onExecute:
            - DATA="{\"data\":{\"teststrategy\":\"manual\",\"project\":\"${int_KeptnIntegration_PROJECT_NAME}\",\"stage\":\"${int_KeptnIntegration_KEPTN_STAGE}\",\"service\":\"${int_KeptnIntegration_SERVICE_NAME}\",\"monitoring\":\"${int_KeptnIntegration_Monitoring}\",\"labels\":{\"buildId\":\"${run_id}\",\"jobname\":\"${pipeline_name}\",\"buildNumber\":\"${run_number}\",\"joburl\":\"${step_url}\" }, \"status\":\"succeeded\",\"result\":\"pass\",\"test\":{\"start\":\"${keptnStart}\",\"end\":\"${keptnEnd}\" },\"evaluation\":{\"start\":\"${starttime}\",\"end\":\"${endtime}\"},\"image\":\"${pipeline_name}\",},\"datacontenttype\":\"application/json\",\"source\":\"Jfrog\",\"specversion\":\"1.0\",\"type\":\"sh.keptn.event.evaluation.triggered\"}"
            - HTTPCODE=$(curl --write-out "%{http_code} --silent --header 'Content-Type:application/json' --location --request POST "${int_KeptnIntegration_API_URL}/v1/event"  -H 'Accept:application/json' --header "x-token:${int_KeptnIntegration_API_TOKEN}" -d "${DATA}")
            - >-
              if [[ "$HTTPCODE" != "200" ]]; then
                exit 1
              fi
            - echo "KEPTN evaluation sent"
          onSuccess:
            - echo "Event properly sent to ${int_dynatraceIntegration_DT_URL}"
          onFailure:
            - echo "Failure"